name: gkd签到

on:
    workflow_dispatch:
    schedule:
        - cron: "0 16 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: wsmud_action

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: "安装依赖包"
              run: pip install requests
            - name: "运行 签到"
              run: python3 gkd.py
              env:
                  SIGNURL: ${{ secrets.SIGNURL }}
                  COOKIE: ${{ secrets.COOKIE }}
                  SERVERCHAN: ${{ secrets.SERVERCHAN }} 
